CREATE DATABASE DBLessons;
CREATE TABLE IF NOT EXISTS Person
(
    PersonID SERIAL PRIMARY KEY NOT NULL,
    Name VARCHAR(20) NOT NULL,
    Surname VARCHAR(20),
    Ptronumic VARCHAR(20),
    Photo VARCHAR(150),
    Description VARCHAR(150),
    DateOfBirth DATE
);
CREATE TABLE IF NOT EXISTS Mark
(
    MarkID SERIAL PRIMARY KEY NOT NULL,
    Type VARCHAR(10) UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS MarkSet
(
    MarkSetID SERIAL PRIMARY KEY NOT NULL,
    PersonID INTEGER NOT NULL,
    MarkID INTEGER NOT NULL,
    FOREIGN KEY (PersonID) REFERENCES Person (PersonID) 
        ON DELETE CASCADE 
        ON UPDATE CASCADE ,
    FOREIGN KEY (MarkID) REFERENCES Mark (MarkID) 
        ON DELETE CASCADE 
        ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS Phone
(
    PhoneID SERIAL PRIMARY KEY NOT NULL,
    PersonID INTEGER NOT NULL,
    PhoneNumber CHAR(11) NOT NULL,
    FOREIGN KEY (PersonID) REFERENCES Person (PersonID) 
        ON DELETE CASCADE
        ON UPDATE SET DEFAULT
);
CREATE TABLE IF NOT EXISTS Email
(
    EmailID SERIAL PRIMARY KEY NOT NULL,
    PersonID INTEGER NOT NULL,
    Adres VARCHAR(30) NOT NULL,
    Domain VARCHAR(15) NOT NULL,
    Local VARCHAR(5) NOT NULL,
    FOREIGN KEY (PersonID) REFERENCES Person (PersonID) 
        ON DELETE CASCADE
        ON UPDATE SET DEFAULT
);

ALTER TABLE Person drop column Photo;
ALTER TABLE Person add Photo VARCHAR(150);